[package]
name = "gun_game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_ecs = "*"
valence = { git = "https://github.com/valence-rs/valence" }
valence_anvil = { git = "https://github.com/valence-rs/valence" }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
